---
# tasks file for install_docker
- name: Creates directory for docker compose cli
  ansible.builtin.file:
    path: /home/{{ item.name}}/.docker/cli-plugins/
    state: directory
  loop: "{{ USER }}"

- name: set permission for docker compose cli
  command: chmod 666 /home/{{ item.name}}/.docker/cli-plugins/
  loop: "{{ USER }}"

- name: Install docker compose cli
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
    dest: /home/{{ item.name}}/.docker/cli-plugins/
    mode: 'u+x,g+x'
  loop: "{{ USER }}"

- name: Set docker compose cli permissions
  command: chmod +x /home/{{ item.name}}/.docker/cli-plugins/
  become: true
  loop: "{{ USER }}"
  
- name: Modify privilege
  become_method: sudo
  shell: 
    cmd: usermod -aG docker {{ item.name }}
  loop: "{{ USER }}"

- name: set permission 
  command: chmod 666 /var/run/docker.sock