---
- hosts: all
  become: yes
  become_user: gregory
  gather_facts: True
  tasks:

  #Stopping container
    - name: Stop the docker container
      docker_container:
        name: Ansible.Semaphore
        state: stopped

  #Removing/Deleting container
    - name: Remove container
      docker_container:
        name: Ansible.Semaphore
        state: absent

  #Removing/Deleting Image
    - name: Remove image
      docker_image:
        name: ansiblesemaphore/semaphore:latest
        state: absent

  #Pull latest version Image
    - name: pull an image
      docker_image:
        name: ansiblesemaphore/semaphore:latest
        source: pull

  #deploy compose file
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: ~/srv/devops/
        files:
        - docker-compose.yml
        recreate: always