---
- name: apache2 listen on port 8081
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
  notify:
    - restart apache2

- name: apache2 virtualhost on port 8081
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
  notify:
    - restart apache2

- name: create virtual host file
  template: src=./virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

- name: apache2 restart
  service: 
    name: apache2 
    state: restarted