---
# tasks file for kubernetes_cluster_uninstall
- name: Stop Docker Container and Clean up nodes
  shell:
    cmd: "docker rm -f $(docker ps -qa)"
  ignore_errors: True

# - name: Unmount kubelet mounts
#   become: true
#   shell:
#     cmd: "for mount in $(mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }') /var/lib/kubelet /var/lib/rancher; do umount $mount; done"
#   ignore_errors: True

- name: Remove Docker Images
  shell:
    cmd: "docker rmi -f $(docker images -q)"
  ignore_errors: True

- name: Remove Docker Volumes
  become: true
  shell:
    cmd: "docker volume rm $(docker volume ls -q)"
  ignore_errors: True

- name: Remove Directories and Files
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - /etc/ceph
    - /etc/cni
    - /etc/rancher
    - /etc/kubernetes
    - /opt/cni
    - /opt/rke
    - /run/secrets/kubernetes.io
    - /run/calico
    - /run/flannel
    - /var/lib/calico
    - /var/lib/etcd
    - /var/lib/cni
    - /var/lib/rancher
    - /var/log/containers
    - /var/log/pods
    - /var/log/pods
    - /var/run/calico
    - /var/lib/kubelet