services:
  devops:
    container_name: devops_container
    hostname: devops_container
    # build:
    #   context: .
    image: ansible:latest
    network_mode: host
    restart: always
    command: ["/bin/sh", "ansible --version"]