---

- hosts: server17a
  gather_facts: False
  connection: local

  tasks:
    - name: copying pihole compose file
      copy:
        src: home/gregory/srv/pihole/docker-compose.yml
        dest: home/gregory/srv/ansible/
      loop:
        - docker-compose.yml