---
- hosts: server17a
  become: yes
  tasks:  
  
  #Copy the compose file
    - name: copy Docker Compose files
      template:
        src: /home/gregory/srv/portainer/docker-compose.yml
        dest: /home/gregory/ansible/srv/portainer/{{ item }}
      loop:
      - docker-compose.yml