---
- hosts: server17a
  become: yes
  tasks:  
  
  #backup container data
    - name: Back-up container data
      copy:
        src: /home/gregory/srv/pihole/etc-pihole
        dest: /home/gregory/ansible/srv/pihole/
        remote_src: yes
        directory_mode: yes