---
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: vm-01
    network_mode: host
    container_name: tailscale
    privileged: true
    environment:
      # TS_AUTH_KEY: $${{ AUTH_KEY }}
      TS_STATE_ARG: "mem:"
      TS_EXTRA_ARGS: tailscale up --login-server=https://headscale.apex-migrations.net --authkey=6c472f5299e20fcfbddeb8b00f24ec7e6cf012509e2212ac
      TS_USERSPACE: false
    volumes:
      - ./tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    cap_add: # Required for tailscale to work
      - NET_ADMIN
      - sys_module
    command: tailscaled
    restart: unless-stopped