---
# tasks file for kubernetes_agent_install 
- name: Create directory if it does not exist
  ansible.builtin.file:
    path: ~/srv/rancher/
    state: directory
    mode: '0777'

- name: Copy Rancher Agent compose file
  copy:
    src: ~/srv/devops/kubernetes/roles/master_install/files/docker-compose.yml
    dest: ~/srv/rancher/docker-compose.yml
    remote_src: false

- name: create and start docker compose services
  community.docker.docker_compose_v2:
    project_src: ~/srv/rancher/