###
#Hier word de verbinding naar de servers opgezet, en de acties uitgevoerd op basis
#van alle mappen aanwezig in de rollen
#Ook word de locatie van de default waardes meegegeven: vars/default.yml
###
---
- name: configure lamp
  hosts: opencart
  become: yes
  become_method: sudo
  vars_files:
    - vars/default.yml
  roles:
    - apache
    - mariadb