---
# tasks file for create_vm
- proxmox_kvm:
    api_user: root@pam
    api_password: laliloe
    api_host: pve
    clone: arbitrary_name
    vmid: 102
    newid: 152
    full: yes
    name: test-vm  # The target VM name
    node: pve
    storage: local-lvm
    format: qcow2

- proxmox_kvm:
    api_user: root@pam
    api_password: laliloe
    api_host: pve
    vmid: 152
    state: started