---
# tasks file for kubernetes_agent_install 
- name: Copy Rancher Agent compose file
  copy:
    src: /home/gregory/srv/devops/kubernetes/roles/agent_install/files/docker-compose.yml
    dest: ~/docker-compose.yml

- name: Run Docker Compose up -d 
  command: docker compose up -d --force-recreate

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled

- name: Set logging
  become: true
  community.general.ufw:
    logging: 'on'

- name: Allow port range 2379-2380
  become: true
  community.general.ufw:
    rule: allow
    port: 2379:2380
    proto: tcp

- name: Allow port 6443
  become: true
  community.general.ufw:
    rule: allow
    port: 6443
    proto: tcp

- name: Allow port 10250
  become: true
  community.general.ufw:
    rule: allow
    port: 10250
    proto: tcp