---
- hosts: vps
  become_user: root
  tasks:
  
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'