---
- hosts: all
  become: yes
  become_user: gregory
  gather_facts: True
  tasks:
  vars:
    myuser: "gregory"
    mypassword: "laliloe"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"