---
- hosts: server17a
  become: yes
  tasks:

  #Copy the compose file
  - name: copy Docker Compose files to remote server
    copy:
      src: /home/gregory/srv/devops/srv/traefik/docker-compose.yml
      dest: /home/gregory/srv/traefik/
    loop:
    - docker-compose.yml

  #Copy the config file
  - name: copy config traefik files to remote server
    copy:
      src: /home/gregory/srv/devops/srv/traefik/traefik.yml
      dest: /home/gregory/srv/traefik//configurations/traefik.yml
    loop:
    - traefik.yml

  #Copy the config file
  - name: copy config traefik files to remote server
    copy:
      src: /home/gregory/srv/devops/srv/traefik/dynamic.yml
      dest: /home/gregory/srv/traefik/configurations/dynamic.yml
    loop:
    - dynamic.yml

  #deploy compose file
  - name: deploy Docker Compose stack on remote server
    docker_compose:
      project_src: /home/gregory/srv/traefik/
      files:
      - docker-compose.yml
      recreate: always