version: "3.3"

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    image: "traefik:latest"
    container_name: traefik.rproxy
    restart: unless-stopped
    command:
      # Enable a http challenge named "myhttpchallenge" and "mytlschallange"
      # - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      # The email to provide to let's encrypt
      - "--certificatesresolvers.mytlschallenge.acme.email=aquiles.craane@gmail.com"
      # Tell it to use our predefined entrypoint named "web"
      # - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web-"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge.entrypoint=web"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      
    ports:
      - "80:80"
      - "443:443"
      - "853:853"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/srv/letsencrypt/:/srv/letsencrypt"
      - "/letsencrypt/:/letsencrypt"
      - "traefik-ssl-certs:/ssl-certs"
      - "./:/etc/traefik/"

    labels:

      - "traefik.enable=true"

      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.cloud-migrations.nl`, `www.traefik.cloud-migrations.nl`)"
      # - "traefik.http.routers.traefik-secure.tls=true"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=production"
      # - "traefik.http.routers.traefik-secure.tls.domains[0].main=erp.cloud-migrations.nl"
      # - "traefik.http.routers.traefik-secure.service=api@internal"
      # - "traefik.http.routers.traefik-secure.entrypoints=web"

      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.cloud-migrations.nl`, `www.traefik.cloud-migrations.nl`)"
      - "traefik.http.routers.traefik-secure.tls.certresolver=production"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080" #port to the webservice
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"

    networks: 
      - web
      - web-secure

networks: 
  web:
    external: true
  web-secure:
    external: true
