---
- hosts: all
  become: yes
  tasks:  
  
  #Copy the compose file
    - name: copy Docker Compose files
      fetch:
        src: /home/gregory/srv/traefik/docker-compose.yml
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - docker-compose.yml

    #Copy the config file
    - name: copy Docker Compose files
      fetch:
        src: /home/gregory/srv/traefik//configurations/traefik.yml
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - traefik.yml

    #Copy the config file
    - name: copy traefik dynamic Configuration
      fetch:
        src: /home/gregory/srv/traefik/configurations/dynamic.yml
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - dynamic.yml