---
- hosts: server17a
  become: yes
  tasks:

  #Stopping container
    - name: Stop the docker container
      docker_container:
        name: traefik.rproxy
        state: stopped

  #Removing/Deleting container
    - name: Remove container
      docker_container:
        name: traefik.rproxy
        state: absent

  #Removing/Deleting Image
    - name: Remove image
      docker_image:
        name: traefik:latest
        state: absent

  #Pull latest version Image
    - name: pull an image
      docker_image:
        name: traefik:latest
        source: pull

  #Copy the compose file
    - name: copy Docker Compose files
      fetch:
        src: /home/gregory/srv/traefik/
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - docker-compose.yml

    #Copy the config file
    - name: copy traefik dynamic Configuration
      fetch:
        src: /home/gregory/srv/traefik/configurations/
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - dynamic.yml

    #Copy the config file
    - name: copy traefik config Configuration
      fetch:
        src: /home/gregory/srv/traefik/configurations/
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - traefik.yml

  #deploy compose file
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: /home/gregory/srv/traefik/
        files:
        - docker-compose.yml
        recreate: always