---
- hosts: localhost
  name: Install docker
  become: yes

  tasks:
  - name: Install docker packages
    remote_user: ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker

  - name: Add Docker s official GPG key
    remote_user: gregory
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker

  - name: Verify that we have the key with the fingerprint
    remote_user: gregory
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker

  - name: Set up the stable repository
    remote_user: gregory
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker

  - name: Update apt packages
    remote_user: gregory
    apt:
      update_cache: yes
    tags:
      - docker

  - name: Install docker
    remote_user: gregory
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker

  - name: Add remote "ubuntu" user to "docker" group
    remote_user: gregory
    user:
      name: "gregory"
      groups: "docker"
      append: yes
    tags:
      - docker
      
  - name: Install docker-compose
    remote_user: gregory
    get_url: 
      url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Set Docker-Compose permissions
    remote_user: gregory
    command: sudo chmod +x /usr/local/bin/docker-compose
