---
- hosts: all
  name: Install docker
  become: false

  tasks: 
  - name: Install docker-compose
    remote_user: gregory
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
      dest: ~/.docker/cli-plugins/
      mode: 'u+x,g+x'

  - name: Set Docker-Compose permissions
    remote_user: gregory
    command: chmod +x ~/.docker/cli-plugins/docker-compose
