---
- hosts: all
  become: yes
  gather_facts: false
  remote_user: gregory
  tasks:
    - name: download docker
      remote_user: gregory
      become_method: sudo
      shell: curl https://get.docker.com | sh
      
    - name: Modify privilege
      remote_user: gregory
      become_method: sudo
      shell: usermod -aG docker $USER

    - name: Change privilege of docker
      remote_user: gregory
      become_method: sudo
      file: dest=/usr/bin/docker mode=+x

    - name: python docker / docker-compse module
      pip:
        name:
            - docker
            - docker-compose