---
# tasks file for tailscale
# - name: Create a temporary directory if it does not exist
#   ansible.builtin.file:
#     path: ~/temp/tailscale/
#     state: directory
#     mode: '0777'
    
# - name: Checkout the git tailscale repo
#   ansible.builtin.git:
#     repo: 'https://github.com/gregoryca/tailscale.dns.git'
#     dest: ~/temp/tailscale/

- name: Create the tailscale directory if it does not exist
  ansible.builtin.file:
    path: "{{ item.folder }}"
    state: directory
    mode: '0777'
  loop: "{{ SOURCE }}"

- name: Copy compose file
  copy:
    src: /home/runner/work/devops/devops/proxmox/roles/tailscale/files/
    dest: "{{ item.folder }}"
    remote_src: false
  loop: "{{ SOURCE }}"

- name: create and start docker compose services
  community.docker.docker_compose_v2:
    project_src: "{{ item.folder }}"
  loop: "{{ SOURCE }}"