version: '3.3'

services:
  mariadb:
      container_name: mariadb.nextcloud
      image: mariadb:latest
      restart: always
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
        - MARIADB_USER=a-grcr
        - MARIADB_DATABASE=nextcloud_db
      volumes:
        - ./data/mariadb:/var/lib/mysql
      networks: 
        - db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin.nextcloud
      #link to the mariadb database. This is required for a connection
      links:
        - mariadb
      environment:
        PMA_HOST: mariadb
        PMA_PORT: 3306
      restart: always
      depends_on:
        - mariadb
      networks: 
        - db
        - web-secure
      labels:
        # enable traefik labels
        - "traefik.enable=true"

        - "traefik.http.routers.phpmyadmindev.rule=Host(`phpmyadmin.cloud-migrations.nl`)"
        - "traefik.http.routers.phpmyadmindev.entrypoints=web-secure"
        - "traefik.http.routers.phpmyadmindev.tls.certresolver=production"
        - "traefik.http.routers.phpmyadmindev.tls=true"
        - "traefik.http.services.phpmyadmindev.loadbalancer.server.port=80" #port to the webservice

        - "traefik.http.routers.phpmyadmindev.middlewares=real-ip-foo@file, authelia-secure@docker"

  app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    links:
        - mariadb
    restart: always
    volumes:
      - ./data/nextcloud:/config
      - /nextcloud-data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - web-secure
      - db

    labels:
       - "traefik.enable=true"

       # web interface
       - "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.cloud-migrations.nl`)"
       - "traefik.http.routers.nextcloud-secure.tls.certresolver=production"
       - "traefik.http.routers.nextcloud-secure.tls=true"
       - "traefik.http.routers.nextcloud-secure.entrypoints=web-secure"

       - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://cloud.cloud-migrations.nl
       - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' cloud.cloud-migrations.nl *.cloud.cloud-migrations.nl
       - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
       - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
       - traefik.http.middlewares.nextcloud.headers.stsPreload=true
       - traefik.http.middlewares.nextcloud.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN
       - traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true
       - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
       - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=https://$${1}/remote.php/dav/
       - traefik.http.middlewares.nextcloud_redirect1.redirectregex.regex=https://(.*)/.well-known/webfinger
       - traefik.http.middlewares.nextcloud_redirect1.redirectregex.replacement=https://$${1}/.well-known/webfinger
       - traefik.http.middlewares.nextcloud_redirect2.redirectregex.regex=https://(.*)/.well-known/nodeinfo
       - traefik.http.middlewares.nextcloud_redirect2.redirectregex.replacement=https://$${1}/.well-known/nodeinfo

       - "traefik.http.routers.nextcloud-secure.middlewares=real-ip-foo@file, nextcloud@docker, nextcloud_redirect@docker, nextcloud_redirect1@docker, nextcloud_redirect2@docker"

       - "traefik.http.services.nextcloud-secure.loadbalancer.server.port=80" #port to the webservice

networks:
  web-secure:
    external: true
  db:
    external: true
