---
- hosts: all
  become: yes
  tasks:  
  
  #Copy the compose file
    - name: copy Docker Compose files
      fetch:
        src: /home/gregory/srv/nextcloud/docker-compose.yml
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - docker-compose.yml

    #Copy the config file
    - name: copy Nginx Configuration
      fetch:
        src: /home/gregory/srv/nextcloud/default
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - default