services:
    rancher-agent:
        privileged: true
        restart: unless-stopped
        network_mode: host
        container_name: rancher.agent
        volumes:
            - /etc/kubernetes:/etc/kubernetes
            - /var/run:/var/run
        image: rancher/rancher-agent:v2.8.3
        command: --server https://kubernetes.apex-migrations.net --token 7fgll78tmzmp8s5mrwwzthjvjlz2khlwx7xsdb6px6lh4j6p66xsd9 --ca-checksum 0f1e331f86af9fc6f5bb8cc6419f0d332c2172fa63bb0ad0b85897786cf12663 --etcd --controlplane --worker
