---
- hosts: server17a
  become: yes
  tasks:

  #Stopping container
    - name: Stop the docker container
      docker_container:
        name: pihole.dns
        state: stopped

  #Removing/Deleting container
    - name: Remove container
      docker_container:
        name: pihole.dns
        state: absent

  #Removing/Deleting Image
    - name: Remove image
      docker_image:
        name: netdata/netdata:latest
        state: absent

  #Pull latest version Image
    - name: pull an image
      docker_image:
        name: netdata/netdata:latest
        source: pull

  #Copy the compose file
    - name: copy Docker Compose files
      fetch:
        src: /home/gregory/srv/netdata/docker-compose.yml
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - docker-compose.yml

  #deploy compose file
    - name: deploy Docker Compose stack
      docker_compose:
        project_src: /home/gregory/srv/pihole/
        files:
        - docker-compose.yml
        recreate: always