---
- hosts: server17a
  become: yes
  tasks:  

  #Copy the compose file
  - name: copy Docker Compose files to remote server
    copy:
      src: /home/gregory/srv/devops/srv/pihole/docker-compose.yml
      dest: /home/gregory/srv/pihole/
    loop:
    - docker-compose.yml

  #deploy compose file
  - name: deploy Docker Compose stack
    docker_compose:
      project_src: /home/gregory/srv/pihole/
      files:
      - docker-compose.yml
      recreate: always