---
- hosts: server17a
  become: yes
  tasks:  
  
  #Copy the compose file
    - name: copy Docker Compose files
      fetch:
        src: /home/gregory/srv/pihole/docker-compose.yml
        dest: ./
        remote_src: yes
        flat: yes
      loop:
      - docker-compose.yml