---
- hosts: server17a
  become: yes
  tasks:    
    - name: pull an image
      docker_image:
        name: pihole/pihole:latest
        source: build
        build:
          path: ./srv/ansible/
    
    - name: Start the containers
      docker_compose:
        project_src: ~./srv/ansible/
        state: present
