---
- hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Install "{{ package_name }}"
      apt:
        name: open-iscsi, nfs-common, qemu-guest-agent
        update_cache: yes
        state: present

    - name: Enable service qemu-guest-agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        enabled: true

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        name: qemu-guest-agent