---
# tasks file for server_management
- name: Install "{{ package_name }}"
  apt:
    name: "{{ package_name }}"
    update_cache: yes
    state: present

- name: Install docker python package
  ansible.builtin.pip:
    name: "{{ docker }}"