---
# tasks file for upgrade_docker_stack

- name: stop and remove docker compose services
  community.docker.docker_compose_v2:
    project_src: ~/srv/{{ DOCKER_STACK_NAME }}
    state: "{{ STATE }}"
  loop: 
    - "{{ STATE }}"
    - "{{ DOCKER_STACK_NAME }}"
  ignore_errors: true

- name: Remove {{ DOCKER_IMAGE }} image
  docker_image:
    name: "{{ DOCKER_IMAGE }}"
    state: "{{ STATE }}"
  loop: 
    - "{{ STATE }}"
    - "{{ DOCKER_IMAGE }}"
  ignore_errors: true
  
- name: pull latest {{ DOCKER_IMAGE }} version
  docker_image:
    name: "{{ DOCKER_IMAGE }}"
    source: pull
  loop: 
    - "{{ STATE }}"
    - "{{ DOCKER_IMAGE }}"

- name: create and start docker compose services
  community.docker.docker_compose_v2:
    project_src: ~/srv/{{ DOCKER_STACK_NAME }}
  loop: 
    - "{{ DOCKER_STACK_NAME }}"