---
# tasks file for server_provisioning_devops
- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

# - name: Create a new regular user with sudo privileges
#   user:
#     name: "{{ item.name }}"
#     state: present
#     groups: "{{ item.groups }}"
#     append: "{{ item.append }}"
#     create_home: "{{ item.create_home }}"
#   loop: "{{ USER }}"

- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  loop: "{{ USER }}"

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'

- name: Install "{{ package_name }}"
  apt:
    name: "{{ package_name }}"
    update_cache: yes
    state: present

- name: Enable and start qemu-guest-agent service
  shell: "systemctl start qemu-guest-agent && systemctl enable qemu-guest-agent"

- name: Install ufw firewall
  ansible.builtin.apt:
    name: ufw
    state: present

- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny

- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Allow all access to port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow all access to port 443
  ufw:
    rule: allow
    port: '443'
    proto: tcp