---
- hosts: cloudservers
  become: yes
  become_user: root
  tasks:
    - name: Another way to call known_hosts
      known_hosts:
        name: dockervm-0   # or 10.9.8.77
        key: dockervm-0.westeurope.cloudapp.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCeVaDOaws+2N6EhJmabw14nI+64RA5I5Q1VFj7AQ8RgKZ/K9+sFSv76fNebdjZHeEgs9haVLiBzP4vMFFg4VsHHbPlCgFqokYvIIWdrEFvHbpD9Y+nwXtO3uv1S84lNaN9Mz1CnbIQiWFrsLfWBLhKqv5r5ANFv01fzlz5QGJ0DyqSfHqmgtPIe9L11PHX/qmmso+IQEGMdoHgi2JT3kzn9l0wNvIZmiYLqMoL9KdIFVWVbcfqOrJdFnryGu/T6076Fomtzyz0EU4JKek6hNNBo3nETQJOuZqCaVCsPmAP3Qow58wUaAoOZ3IOQ9nADEVlunqz1zjSKLpNUBHuZubyxvq/tSd6GREWL47T1JLM4VdyT88FVvgRwqjrqrybYj61357dtOrVgjNfsuk4Ev1hzYjlVlUlX65vTagQXN3dDngaGnRo8faBqXSWfzNGH17SzyphKg0DS5axzJvy+w0EYK5tpXWjfoKk3eVcfN5bAVMgolgR3HHgXchSJGXgvU= gregory@dev-machine  # some key gibberish
        path: /etc/ssh/ssh_known_hosts
        state: present