---
- hosts: cloudservers
  become: yes
  become_user: root
  tasks:
    - name: Another way to call known_hosts
      known_hosts:
        name: dockervm-0   # or 10.9.8.77
        key:   # some key gibberish
        path: /etc/ssh/ssh_known_hosts
        state: present