---
- name: user module demo
  hosts: opencart
  become: true
  vars:
    myuser: "gregory"
    mypassword: "laliloe"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"