---
- hosts: vps
  gather_facts: True
  tasks:

    - name: copying file with playbook
      become: true 
      copy:
        src: /home/gregory/.ssh/id_ed25519
        dest: /home/GregoryacDevOps/.ssh/id_ed25519
        remote_src: yes