---
- hosts: azure17a
  name: Install python3-pip
  become: yes

  tasks:

    - name: Install pip
      apt:
        name: python-pip
        update_cache: yes
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: yes
        state: present