---
- hosts: all
  become: yes
  become_user: {{user}}
  gather_facts: True
  tasks:

  tasks:

    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: yes
        state: present
