---
- hosts: all
  become: yes
  become_user: gregory
  gather_facts: True
  tasks:

      - name: Install UFW  (state=present is optional)
        ansible.builtin.apt:
          name: ufw
          state: present