---
- hosts: all
  become: yes
  become_user: gregory
  gather_facts: True
  tasks:
  
    - name: set permission 
      remote_user: gregory
      become: yes
      command: chmod 666 /var/run/docker.sock