---
- hosts: server17a0
  become: yes
  gather_facts: True
  tasks:

    - name: stop port 6443 from listening
      become_user: gregory
      become_method: sudo
      shell:
        cmd: "sudo fuser -k 6443/tcp"
      ignore_errors: True