---
- hosts: server17a0
  become: yes
  gather_facts: True
  tasks:

    - name: stop port 6443 from listening
      remote_user: gregory
      become_method: sudo
      shell:
        cmd: "fuser -k 6443/tcp"
      ignore_errors: True