version: '3.1'
services:
  web:
    container_name: Apex-migrations_erp
    image: odoo:latest
    depends_on:
      - db
    networks:
      - web-secure
    restart: always
    labels:     
      - "traefik.enable=true"
      - "traefik.http.routers.odoo-secure.rule=Host(`erp.cloud-migrations.nl`, `www.erp.cloud-migrations.nl`)"
      - "traefik.http.routers.odoo-secure.tls.certresolver=production"
      - "traefik.http.routers.odoo-secure.tls=true"
      - "traefik.http.services.odoo.loadbalancer.server.port=8069" #port to the webservice
      - "traefik.http.routers.odoo-secure.entrypoints=web-secure"
    volumes:
       - '/home/gregory/srv/odoo:/mnt/odoo-addons/'

  db:
    container_name: Apex-migrations_erp_db1
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - web-secure
    
networks:
  web-secure:
    external: true