services:
    rancher-agent:
        privileged: true
        restart: unless-stopped
        network_mode: host
        container_name: rancher.agent
        volumes:
            - /etc/kubernetes:/etc/kubernetes
            - /var/run:/var/run
        image: rancher/rancher-agent:latest
        command: --server https://rancher.apex-migrations.net --token rsmwnfffmxrs4ztkg8s4vct97gnzxcvmjh8qk9whddcwnb9t74mpsv --ca-checksum 23fa0101a50415e106cf3611ededd229d2bd4037f76a2afaa81d43365ada092e --etcd --controlplane --worker