name: Deploy Nextcloud docker-compose

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Start Nextcloud stack
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: cd /home/gregory/srv/nextcloud/ && docker-compose up -d --force-recreate