name: Deploy

on:
  # Triggers this Action on push or pull request events on the "main" branch and when manually requested from the "Actions" tab
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # deploy_code:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Runs pihole docker-compose
  #       uses: actions/checkout@v3

  #       run: ssh gregory@apex-migrations.ddns.net:44 "cd /home/gregory/srv/pihole/ && docker-compose up -d"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: cd /home/gregory/srv/pihole/ && docker-compose up -d --force-recreate