name: Deploy Traefik docker-compose

on:
  push:
    branches:
      - 'traefik'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Start Traefik stack
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: cd /home/gregory/srv/devops/srv/traefik/ && ansible-playbook deploy_traefik.yml