######################################################
# This is a basic workflow to Deploy a traefik stack #
######################################################
name: Deploy Tailscale

on:
  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

defaults:
  run:
    working-directory: ./devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker
      # You may pin to the exact commit or the version.
      # uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19
        uses: docker/setup-docker-action@v4.3.0
        with:
          # Docker CE version. (e.g, v24.0.9)
          version: latest
    
      - name: Setup Docker Compose
      # You may pin to the exact commit or the version.
      # uses: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746
        uses: docker/setup-compose-action@v1.2.0

      - name: Docker Compose Deployment
        run: cd github && docker compose up -d

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      # - name: Run Ansible Playbook
      #   env:
      #     # ANSIBLE_USER: root
      #     ANSIBLE_HOST_KEY_CHECKING: false
      #   run: |
      #     ansible-playbook -i proxmox/proxmox_inventory proxmox/install_tailscale.yml --private-key "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" -u root


      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          # Required, playbook filepath
          playbook: install_tailscale.yml
          # Optional, directory where playbooks live
          directory: ./proxmox
          # Optional, ansible configuration file content (ansible.cfg)
          configuration: |
            [defaults]
            callbacks_enabled = ansible.posix.profile_tasks, ansible.posix.timer
            stdout_callback = yaml
          # Optional, SSH private key
          key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [proxmox]
            pve ansible_host=100.64.0.6

            [proxmox:vars]
            ansible_ssh_user=root