######################################################
# This is a basic workflow to Deploy a traefik stack #
######################################################
name: Deploy Tailscale

on:
  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Setup Docker
      # You may pin to the exact commit or the version.
      # uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19
        uses: docker/setup-docker-action@v4.3.0
        with:
          # Docker CE version. (e.g, v24.0.9)
          version: latest
    
      - name: Docker Setup Compose
      # You may pin to the exact commit or the version.
      # uses: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746
        uses: docker/setup-compose-action@v1.2.0

      - name: Docker-compose Deployment
        run: cd github && docker compose up -d