##############################################
# This is a basic workflow to update servers #
##############################################
name: Fix Linux Server DNS

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4.1.1

      - name: Setup Docker Compose
      # You may pin to the exact commit or the version.
      # uses: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746
        uses: docker/setup-compose-action@v1.2.0
    
      - name: Run Tailscale Docker Compose File
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
            compose-file: "./github/files/docker-compose.yml"

      - uses: dawidd6/action-ansible-playbook@v2
        name: Append Tailscale DNS server to Tailscale int using ansible
        with:
          playbook: dns_fix.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          directory: ./linux/ops
          inventory: |
            [localhost]
            127.0.0.1 ansible_connection=local

      - uses: dawidd6/action-ansible-playbook@v2
        name: Append Tailscale DNS server on the host, to Tailscale int using ansible
        with:
          playbook: fix_dns.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          directory: ./linux/roles
          inventory: |
            [home]
            srv-17a ansible_host=srv-17a.headscale.node ansible_ssh_user=gregory
            nextcloud-lvm ansible_host=nextcloud.headscale.node ansible_ssh_user=gregory
