name: Retrieve SSH Keys

on:
  # Triggers this Action on push or pull request events on the "main" branch and when manually requested from the "Actions" tab
  push:
    branches: [ master ]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve SSH keys
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTSRV }}
        username: ${{ secrets.USERNAME }}
        password: laliloe4life_
        port: 22
        script: ssh-copy-id -i /home/${{ secrets.USERNAME }}/.ssh/id_rsa.pub 51.145.209.15
