##############################################
# This is a basic workflow to install Docker #
##############################################
name: Update Server(s)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Run playbook
        uses: actions/checkout@v3

      ########################################################
      # Deploys an ansible script to update the server stack #
      ########################################################
      - uses: dawidd6/action-ansible-playbook@v2
        name: Provision a server with Docker
        with:
          ###############################
          # Required, playbook filepath #
          ###############################
          playbook: provision_docker.yml
          ############################################
          # Optional, directory where playbooks live #
          ############################################
          directory: ./docker
          ###################
          # SSH private key #
          ###################
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          ###########################
          # inventory file contents #
          ###########################
          inventory: |
            [linux]
            server17a ansible_host=SRV-01.WESTEUROPE.CLOUDAPP.AZURE.COM ansible_port=22
            
            ansible_user = ${{ secrets.USERNAME }}
            ansible_sudo_pass = laliloe4life_
