##############################################
# This is a basic workflow to update servers #
##############################################
name: Update Linux Server(s) - roles

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run playbook
        uses: actions/checkout@v4.1.1

      - name: Setup Docker Compose
      # You may pin to the exact commit or the version.
      # uses: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746
        uses: docker/setup-compose-action@v1.2.0
    
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
            compose-file: "./github/files/docker-compose.yml"

      ########################################################
      # Deploys an ansible script to update the server stack #
      ########################################################
      - uses: dawidd6/action-ansible-playbook@v2
        name: Provision Docker
        with:
          playbook: dns_fix.yml
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          directory: ./linux/ops
          inventory: |
            [localhost]
            127.0.0.1 ansible_connection=local

      - uses: dawidd6/action-ansible-playbook@v2
        name: Update Servers
        with:
          playbook: update_server.yml
          key: ${{secrets.ANSIBLE_SSH_PRIVATE_KEY}}
          directory: ./linux/roles/
          inventory: |
            [server17a]
            server17a ansible_host=srv-17a.headscale.node

            [vps]
            vps ansible_host=${{ secrets.VPS_HOST }} ansible_user=${{ secrets.VPS_USER }}
