##############################################
# This is a basic workflow to update servers #
##############################################
name: Update Linux Server(s) - roles

on:
  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run playbook
        uses: actions/checkout@v4.1.1

      - uses: dawidd6/action-ansible-playbook@v2
        name: Update Servers
        with:
          playbook: update_server.yml
          key: ${{ secrets.PRIVATE_KEY }}
          directory: ./linux/roles/
          inventory: |
            [all]
            dc-srv-01.apex-migrations.net ansible_user=${{ secrets.VPS_USER }}
            apex-migrations.hopto.org ansible_port=${{ secrets.PORT }} ansible_user=${{ secrets.USER }}