##############################################
# This is a basic workflow to update servers #
##############################################
name: Update Portainer

on:
  push:
    branches: [ "dev", "development" ]
  pull_request:
    branches: [ "master" ]

  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Run playbook
        uses: actions/checkout@v3

      ########################################################
      # Deploys an ansible script to update the server stack #
      ########################################################
      - uses: dawidd6/action-ansible-playbook@v2
        name: Update Portainer stack
        with:
          ###############################
          # Required, playbook filepath #
          ###############################
          playbook: update_portainer.yml
          ############################################
          # Optional, directory where playbooks live #
          ############################################
          directory: ./srv/portainer/
          ###################
          # SSH private key #
          ###################
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          ###########################
          # inventory file contents #
          ###########################
          inventory: |
            [linux]
            server17a ansible_host=${{ secrets.HOST }} ansible_port=${{ secrets.PORT }}
            
            [azure]
            app-srv-01 ansible_host=${{ secrets.AZURE_HOST }} ansible_port=${{ secrets.AZURE_PORT }}
            
            [linux:vars]
            ansible_user = ${{ secrets.USERNAME }}
            ansible_sudo_pass = ${{ secrets.PASSWORD }}
            
            [azure:vars]
            ansible_user = ${{ secrets.USERNAME }}
            ansible_ssh_pass=${{ secrets.AZURE_PASSWORD }}
            ansible_sudo_pass=${{ secrets.AZURE_PASSWORD }}