##############################################
# This is a basic workflow to update servers #
##############################################
name: Update Linux Server(s) - roles

on:
  #################################################################
  # Allows you to run this workflow manually from the Actions tab #
  #################################################################
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #################################################################################
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it #
      #################################################################################
      - name: Run playbook
        uses: actions/checkout@v4.1.1

      ########################################################
      # Deploys an ansible script to update the server stack #
      ########################################################
      - uses: dawidd6/action-ansible-playbook@v2
        name: Update Servers
        with:
          ###############################
          # Required, playbook filepath #
          ###############################
          playbook: update_server.yml
          ############################################
          # Optional, directory where playbooks live #
          ############################################
          directory: ./linux/roles/
          ###################
          # SSH private key #
          ###################
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          ###########################
          # inventory file contents #
          ###########################
          inventory: |
            linux:
              hosts:
                server17a ansible_host=${{ secrets.HOST }} ansible_port=${{ secrets.PORT }}
                dc-srv-01 ansible_host=${{ secrets.VPS_HOST }}
            
            linux:vars
              hosts:
                ansible_user=${{ secrets.HOME_USER }}
                ansible_ssh_private_key_file=${{ secrets.HOME_PRIVATE_KEY }}
                ansible_user=${{ secrets.VPS_USER }}
                ansible_ssh_private_key_file=${{ secrets.VPS_PRIVATE_KEY }}